vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.cindent = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.number = true
vim.opt.termguicolors = true
vim.opt.statuscolumn = "%l%s"
vim.opt.signcolumn = "yes:1"
vim.opt.list = true
vim.opt.listchars = { tab = "» ", trail = "·", nbsp = "␣", extends = "…" }
vim.opt.lazyredraw = true
vim.opt.title = true
vim.opt.linebreak = true
vim.opt.breakindent = true
vim.opt.pumheight = 8
vim.opt.scrolloff = 5
vim.opt.undofile = true
vim.opt.showmode = false
vim.opt.spelllang = { "en_us", "de_20" }
vim.opt.completeopt = { "menuone", "noselect", "noinsert" }
vim.opt.confirm = true
vim.opt.shortmess = "Ic"
vim.opt.exrc = true
vim.mouse = "a"
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
